### ISSUE TITLE
Very low eigenvalues when kernel is manually set to normalized_angle

### ISSUE THREAD

**Issue by Bronte-Mckeown** [MICA-MNI/BrainSpace#10]
When I follow [this](https://brainspace.readthedocs.io/en/latest/python_doc/auto_examples/plot_tutorial1.html#sphx-glr-python-doc-auto-examples-plot-tutorial1-py) tutorial, I noticed that the default setting for kernel is actually None instead of normalised angle as stated in the tutorial. 

If I manually set kernel = normalised angle instead of leaving it to the default then the lambdas have very low values. Is this expected? 

This is the code from the tutorial when the kernel is set to default (None) and when the kernel is set to 'normalized_angle:

`
# import warnings
warnings.simplefilter('ignore')

from brainspace.datasets import load_group_fc, load_parcellation, load_conte69
# First load mean connectivity matrix and Schaefer parcellation
conn_matrix = load_group_fc('schaefer', scale=400)
labeling = load_parcellation('schaefer', scale=400, join=True)

# and load the conte69 hemisphere surfaces
surf_lh, surf_rh = load_conte69()
from brainspace.gradient import GradientMaps

# Ask for 10 gradients (default)
gm = GradientMaps(n_components=10, random_state=0)
gm.fit(conn_matrix)
import matplotlib.pyplot as plt
plt.scatter(range(gm.lambdas_.size), gm.lambdas_)

# Ask for 10 gradients (normalized_angle)
gm = GradientMaps(n_components=10,kernel = 'normalized_angle', random_state=0)
gm.fit(conn_matrix)
import matplotlib.pyplot as plt
plt.scatter(range(gm.lambdas_.size), gm.lambdas_)
`
I have attached the figure which plots both the default (blue) and the normalized_angle (orange).

![comparison_tutorial](https://user-images.githubusercontent.com/44265831/72432473-0d3a5880-378f-11ea-97d4-433bb50552f2.png)

**Comment by ReinderVosDeWael** [comment]
Hi Bronte,

Thanks for catching this issue. We'll be sure to resolve this in our next update. Explicitly defining your kernel should resolve any issue you may have.

Regarding the eigenvalues, for purposes of component selection I don't think you should pay much attention to the absolute value of your eigenvalues, but rather at their values relative to each other. 

Hope that helps,

R
