### ISSUE TITLE
If there is way to inspect the variance explained by each gradient using BrainSpace?

### ISSUE THREAD

**Issue by hyw5402** [MICA-MNI/BrainSpace#100]
* **What are you trying to do?**
Want to inspect the variance of each gradient
* **If you've tried running this with BrainSpace code already, how did you do so and what went wrong?**
Yes, I have run BrainSpace code. The code run smoothly at last. However, I want to inspect the variance of each gradient.
* **Please tell us about your computing environment:**
 Ubuntu 20
* **Other information**

**Comment by OualidBenkarim** [comment]
Yes, check the `lambdas__` property of the GradientMaps object. See the last figure in this [tutorial](https://brainspace.readthedocs.io/en/latest/python_doc/auto_examples/plot_tutorial1.html#sphx-glr-python-doc-auto-examples-plot-tutorial1-py)
