### ISSUE TITLE
Template gradient maps

### ISSUE THREAD

**Issue by seunggookim** [MICA-MNI/BrainSpace#101]
* **What are you trying to do?**
I'm trying to resample the template gradient map included in your toolbox onto the Freesurfer template surfaces (`fsaverage`) following the [HCP wiki instruction](https://wiki.humanconnectome.org/download/attachments/63078513/Resampling-FreeSurfer-HCP.pdf). From the instruction, it seems that I would need GIFTI files of the "fs-LR-32k" surfaces with the scalar maps. In your toolbox, filenames have a prefix of "conte69_32k": 
`matlab/datasets/template_gradients/conte69_32k_fc_gradient1.csv`
`matlab/datasets/surfaces/conte69_32k_left_hemisphere.gii`
I'm not familiar with the HCP name conventions. Is "conte69-32k" a name of a template surface that is also referred to as "fs-LR-32k"? Can I just create new GIFTI files using the included GIFTI and CSV files? If not, you provide the original GIFTI files that you used to create the included CSV files?

* **If you've tried running this with BrainSpace code already, how did you do so and what went wrong?**

* **Please tell us about your computing environment:**
  
* **Other information**

**Comment by OualidBenkarim** [comment]
Yes, I think you could use the same instructions for the conte69_32k
