### ISSUE TITLE
How to save the image returned by the plot_hemispheres function to the local machine?

### ISSUE THREAD

**Issue by YH2010** [MICA-MNI/BrainSpace#103]
I try to save the image by the following code, but rise the bug, please help me, thanks!

`from brainspace.plotting.surface_plotting import plot_hemispheres`
`from PIL import Image`
`import matplotlib.pyplot as plt`

`# Generate the image`
`img = plot_hemispheres(... ,embed_nb = True)`

`# Save the image to a file`
`img.save('./result/image.png')`
`img.savefig('./result/image.png')`

**AttributeError: 'Image' object has no attribute 'save'/ 'savefig'**

**Comment by OualidBenkarim** [comment]
Use it like this:

```python
plot_hemispheres(... ,screenshot=True, filename='./result/image.png')
```
