### ISSUE TITLE
Difference in kernel default settings Matlab vs Python

### ISSUE THREAD

**Issue by biancaserio** [MICA-MNI/BrainSpace#104]
Hi,

I wanted to flag an inconsistency between your Python and Matlab packages. When comparing the source code for GradientMaps of Python (https://brainspace.readthedocs.io/en/latest/_modules/brainspace/gradient/gradient.html#GradientMaps) and MATLAB (https://github.com/MICA-MNI/BrainSpace/blob/master/matlab/%40GradientMaps/GradientMaps.m), it seems like the default kernel parameter is different (None for Python, Normalized Angle for MATLAB).

Thanks,

Bianca

**Comment by OualidBenkarim** [comment]
Thanks, @biancaserio. We'll try to converge on this one for the next release
