### ISSUE TITLE
I am trying to use a custom parcelation different from the example

### ISSUE THREAD

**Issue by acamargofb** [MICA-MNI/BrainSpace#105]
I am trying to use a different dataset for the atlas, which was give in another issue:
I followed all the steps that was provided in that ticket, but the last step is not working:

`data = datasets.fetch_development_fmri(n_subjects=1)
fmri_filenames = data.func[0]

from nilearn.input_data import NiftiLabelsMasker
masker = NiftiLabelsMasker(labels_img=atlas_filename, standardize=True,
                           memory='nilearn_cache', verbose=5)

time_series = masker.fit_transform(fmri_filenames)  # time_series is (168, 1000)

import numpy as np
conn_matrix = np.corrcoef(time_series.T)  # conn_matrix is 1000x1000

print(conn_matrix.shape)

from brainspace.gradient import GradientMaps
Gsub = GradientMaps(n_components=10, random_state=0, alignment="procrustes",
                      approach="dm")
Gsub.fit(conn_matrix, sparsity=0.9)  # shape of Gsub.gradients_[:, 0] is 1000

wd_grad_label = '/media/zewang/loc10T/Research/Gradient/CBIG-master/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations/FreeSurfer5.3/fsaverage5/label/'

import nibabel as nb

surf_labels_lh = nb.freesurfer.read_annot( wd_grad_label + 'lh.Schaefer2018_1000Parcels_7Networks_order.annot')[0]
surf_labels_rh = nb.freesurfer.read_annot( wd_grad_label + 'rh.Schaefer2018_1000Parcels_7Networks_order.annot')[0]
surf_labels_rh[surf_labels_rh != 0] += 500  # different labels for lh and rh
surf_labels = np.concatenate([surf_labels_lh, surf_labels_rh])

mask = surf_labels != 0  # discard medial wall

from brainspace.utils.parcellation import map_to_labels
grad = map_to_labels(Gsub.gradients_[:, 0], surf_labels, mask=mask, fill=np.nan)

from brainspace.plotting import plot_hemispheres
plot_hemispheres(surf_labels_lh, surf_labels_rh, array_name=[surf_labels, grad], 
    size=(1200, 400),  cmap=['tab20', 'viridis_r'], color_bar=True, 
    zoom=1.5, label_text=['Schaefer\n1000', 'First\ngradient'])
`

I am getting this error:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_24290/2584315120.py in <module>
      2 plot_hemispheres(surf_labels_lh, surf_labels_rh, array_name=[surf_labels, grad], 
      3     size=(1200, 400),  cmap=['tab20', 'viridis_r'], color_bar=True,
----> 4     zoom=1.5, label_text=['Schaefer\n1000', 'First\ngradient'])

~/Aldo/Research/code/BrainSpaceEnv/lib/python3.7/site-packages/brainspace/vtk_interface/decorators.py in _wrapper_wrap(*args, **kwds)
     39         def _wrapper_wrap(*args, **kwds):
     40             args, kwds = _wrap_input_data(args, kwds, *xargs, skip=skip)
---> 41             data = func(*args, **kwds)
     42             return data
     43         return _wrapper_wrap

~/Aldo/Research/code/BrainSpaceEnv/lib/python3.7/site-packages/brainspace/plotting/surface_plotting.py in plot_hemispheres(surf_lh, surf_rh, array_name, color_bar, color_range, label_text, layout_style, cmap, nan_color, zoom, background, size, interactive, embed_nb, screenshot, filename, scale, transparent_bg, **kwargs)
    551         layout = [layout] * len(array_name)
    552         array_name2 = []
--> 553         n_pts_lh = surf_lh.n_points
    554         for an in array_name:
    555             if isinstance(an, np.ndarray):

AttributeError: 'numpy.ndarray' object has no attribute 'n_points'

**Comment by OualidBenkarim** [comment]
Hi @acamargofb 

This is because you are providing arrays (i.e., **`surf_labels_lh`, `surf_label_rh`**) instead of surfaces for the left and right hemispheres :

```python
# instead of 
plot_hemispheres(surf_labels_lh, surf_labels_rh, ...)

# you need
plot_hemispheres(surf_lh, surf_rh, ...)
```
See [Tutorial 1](https://brainspace.readthedocs.io/en/latest/python_doc/auto_examples/plot_tutorial1.html#sphx-glr-python-doc-auto-examples-plot-tutorial1-py) or [read_surface](https://brainspace.readthedocs.io/en/latest/generated/brainspace.mesh.mesh_io.read_surface.html#brainspace.mesh.mesh_io.read_surface) if you want to use your own surfaces

**Comment by acamargofb** [comment]
Thanks, for the information, my problem is solved

**Comment by AstonshisL** [comment]
Hi,I have some similar problems and wonder if  you can help me.
I try to use structural MRI data to plot the surface in destrieux atalas，but the result shows that the rh and lh are not symmetrical.
correlation matrix（148*148）.
![ZF0J6FGW9}1E U6YRUF@BUS](https://github.com/MICA-MNI/BrainSpace/assets/115601165/2521b25f-b789-43bc-85fd-5f5ffbf4a57e)


```
code：
**atlas = datasets.fetch_atlas_surf_destrieux()**
regions = atlas['labels'].copy()
masked_regions = [b'Medial_wall', b'Unknown']
masked_labels = [regions.index(r) for r in masked_regions]
for r in masked_regions:
    `regions.remove(r)`
labeling = np.concatenate([atlas['map_left'], atlas['map_right']])
mask = ~np.isin(labeling, masked_labels)
# Distinct labels for left and right hemispheres
lab_lh = atlas['map_left']
labeling[lab_lh.size:] += lab_lh.max() + 1
gm = GradientMaps(n_components=2, random_state=0,alignment='procrustes')
correlation_matrix = correlation_matrix.values
gm.fit(correlation_matrix)
# Load fsaverage5 surfaces
**surf_lh, surf_rh = load_fsa5()**
from brainspace.utils.parcellation import map_to_labels
grad = [None] * 2
for i in range(2):
    grad[i] = map_to_labels(gm.gradients_[:, i], labeling, mask=mask)

plot_hemispheres(surf_lh, surf_rh, array_name=grad, size=(1200, 400), cmap='viridis_r',
                 color_bar=True, label_text=['Grad1', 'Grad2'], zoom=1.55)
```


Why is there a left-right asymmetry?I have been puzzled about this problem for a long time, please help me!!
