### ISSUE TITLE
How to show the results in structural template like MNI space

### ISSUE THREAD

**Issue by acamargofb** [MICA-MNI/BrainSpace#109]
I am trying to show the results of the alignment of gradients in a structural template like MNI space. Does somebody know how to do it?

Thanks a lot,

Aldo Camargo

**Comment by zihuaihuai** [comment]
Hi Aldo,

Thanks for your issue. Please refer to this tutorial and related function api settings: "https://brainspace.readthedocs.io/en/latest/python_doc/auto_examples/plot_tutorial2.html#sphx-glr-python-doc-auto-examples-plot-tutorial2-py"

Hope this could help you,

Best
