### ISSUE TITLE
How can I compute the gradient only for one specific mask

### ISSUE THREAD

**Issue by acamargofb** [MICA-MNI/BrainSpace#114]
I am trying to compute the gradient only for a specific ROI, for example frontal lobe. How can I do that with this toolbox?
There is one paper that they did that: https://alzres.biomedcentral.com/articles/10.1186/s13195-023-01228-3

Thanks a lot in advance and have a nice day,

Aldo

**Comment by zihuaihuai** [comment]
I apologize for any confusion, but this issues section is intended for discussing bugs and feature requests related to the package. Thank you for your understanding.
