### ISSUE TITLE
Python Package Issue: Error with Affinity Matrix Containing NaN or Inf Values

### ISSUE THREAD

**Issue by y0ungeunii** [MICA-MNI/BrainSpace#115]
I attempted to generate gradients using mpc_dm() and plot them onto the brain mask using plot_hemispheres(). However, I encountered an error message: **ValueError: Affinity matrix contains NaN or Inf values. Common causes of this include NaNs/Infs or rows of zeros in the input matrix**.

I tried running the same code on another workstation, and it worked without any issues. The only difference between the workstations was the version of some Python packages, such as _pandas_ and _nibabel_. For instance, on the workstation with pandas version 1.4.4, nibabel version 4.0.2, and seaborn version 0.11.2, the code worked fine. However, on the workstation with pandas version 2.0.3, nibabel version 5.1.0, and seaborn version 0.13.0, the code didn't work, despite having higher versions of Python packages.

According to your website, there were no specific requirements mentioned for those Python packages. So, do we need specific requirements for those Python packages? Also, I'm curious about the cause of the error. Thank you!

**Comment by nimzodisaster** [comment]
I am getting this too.

**Comment by jordandekraker** [comment]
Same. @zihuaihuai can you take a look at this when you get the chance? It's fairly high priority I would say.

**Comment by zihuaihuai** [comment]
working in this right now. There are tons of bugs need to be fix with vtk version 9 and python 3.8+

**Comment by zihuaihuai** [comment]
This issue has been fixed, if you have urgency to use this package please git clone this repo and install the pakcage locally by using this command in your virtual env
`pip install -e .`
