### ISSUE TITLE
Recommendation

### ISSUE THREAD

**Issue by LPNC-LANG** [MICA-MNI/BrainSpace#116]
* **What are you trying to do?**
I"m running gradient analysis onto phase-locking networks obtained from source-space MEG data. I have a 52-parcel resolution but am not particularly interested in identifying fine-grained functional boundaries anyway, I'm just looking for a way to embed each connectivity matrix into a one-dimensional array for later statistical analysis.
Relatedly, I couldn't find definitive recommendations on how the choice of kernels and dimensionality reduction algorithm may affect the output? What would you recommend in my case?

**Comment by zihuaihuai** [comment]
I apologize for any confusion, but this issues section is intended for discussing bugs and feature requests related to the package. Thank you for your understanding.
