### ISSUE TITLE
Some questions about matlab package

### ISSUE THREAD

**Issue by Doc-LI-desgin** [MICA-MNI/BrainSpace#126]
* **What are you trying to do?**
Now, I am trying to perform the [Tutorial 1: Building your first gradient],   When I enter the following line of code into MATLAB, I get an error using the load function and the "schaefer_400_conte69.csv" cannot be read. The code is as follows: % First load mean connectivity matrix and Schaefer parcellation conn_matrix = load_group_fc('schaefer',400); labeling = load_parcellation('schaefer',400); 
But I've downloaded all the sample data
What should I do about this?

**Comment by zihuaihuai** [comment]
Hi,

It works fine on my end. I suggest reinstalling the toolbox, as I suspect the folder may be damaged. The file you're looking for should be located in datasets/parcellations/schaefer_400_conte69.csv. Please double-check if the file exists in this location.
