### ISSUE TITLE
What is the input for GradientMaps.fit?

### ISSUE THREAD

**Issue by kaurao** [MICA-MNI/BrainSpace#129]
* **What are you trying to do?**

Calculate gradients using a matrix `X` with shape `(n_samples, n_feat)`.

* **If you've tried running this with BrainSpace code already, how did you do so and what went wrong?**

Nothing went wrong but the usage as done in the literature and the code documentation is confusing.

* **Please tell us about your computing environment:**

Python 3.11 on Linux.
  
* **Other information**

Mostly the literature including the Margulies paper hint that the input should be a similarity matrix and it seems like that is how it is used in published works. However the documentation says:

```
x : ndarray or list of arrays, shape = (n_samples, n_feat)
            Input matrix or list of matrices.
```
permalink: https://github.com/MICA-MNI/BrainSpace/blob/6f2dff9b6a1d08e8353de15ae0216facdb85a71b/brainspace/gradient/gradient.py#L131C49-L131C66

What should be the input to `.fit`?
- `X`
- Something like `corr(X)`

**Comment by zihuaihuai** [comment]
Thank you for bringing this to our attention! You’re absolutely right—there is an issue with the description, and we’ll take a closer look at how to improve the wording for better clarity.

For the actual usage, you can input a connectivity matrix (e.g., FC) as demonstrated in this tutorial: [BrainSpace Tutorial](https://brainspace.readthedocs.io/en/latest/python_doc/auto_examples/plot_tutorial1.html#sphx-glr-python-doc-auto-examples-plot-tutorial1-py).

Let us know if you have further questions or suggestions!
