### ISSUE TITLE
Custom/other parcellations

### ISSUE THREAD

**Issue by AngelikaZa** [MICA-MNI/BrainSpace#17]
Dear BrainSpace team,

Thank you for an amazing tool and really clear documentation!

Just a quick question that I wasnt able to resolve from the docs: 
Is there a way to load a custom parcellation for visualisation purposes?

A more granular functional parcellation Schaefer 1000 as well as other anatomical parcellations such as Glasser might be useful and the current available parcellations are slightly limiting. 

Thank you in advance for your help 

Bw
Angelika

**Comment by ReinderVosDeWael** [comment]
Hi Angelika,

The `load_parcellation` function only supports loading the parcellations used in our manuscript. See the [MATLAB](https://brainspace.readthedocs.io/en/latest/pages/matlab_doc/data_loaders/load_parcellation.html) and/or [Python](https://brainspace.readthedocs.io/en/latest/generated/brainspace.datasets.load_parcellation.html#brainspace.datasets.load_parcellation) documentation for the full list of available parcellations. If you wish to use another parcellation you'll have to find it elsewhere. 

Our visualization tools support any parcellation. If you download the Schaefer 1000 parcellation and load it, then `plot_hemispheres` will be able to plot your data. See the [MATLAB](https://brainspace.readthedocs.io/en/latest/pages/matlab_doc/examples/tutorial_1_gradient_creation.html) and/or [Python](https://brainspace.readthedocs.io/en/latest/python_doc/auto_examples/plot_tutorial1.html) tutorials 1 for an example on how to plot parcellated data.

Hope that helps,
Reinder

**Comment by AngelikaZa** [comment]
Hi Reinder, 
Thank you for the prompt reply.
I did use the mesh.io to load a custom parcellation. Plot_hemispheres works to visualise the parcellation itself but not when trying to visualise the resulting gradient - getting an "array is incorrect shape" error. Exporting the gradient and visualising with nilearn works fine, as does pysurfer. 
I think it might be useful to include more or custom parcellations in future releases though! 
Thanks again
Neal
Angelika

**Comment by ReinderVosDeWael** [comment]
Hi Angelika, 

Would you mind providing a minimal working example of the code you used that resulted in this error? Visualizing gradients with custom parcellations _should_ work, so it'd be good for us to know what's causing this error.

Cheers,

Reinder

**Comment by AngelikaZa** [comment]
Hi Reinder

Below an example:
conn_matrix I have built with nilearn using the schaefer 1000 atlas.
plot_hemispheres(surf_lh,surf_rh, size=(800, 200)) works fine with the atlas below, only gradient visualisation doesnt.

Gsub = GradientMaps(n_components=10, random_state=0, alignment="procrustes", approach="dm") ### aligned to a template gradient
# fit gradient
Gsub.fit(conn_matrix, sparsity=0.9) 

# Load atlas
dataset = datasets.fetch_atlas_schaefer_2018(n_rois=1000, yeo_networks=7, resolution_mm=1)
atlas_filename = dataset.maps
labels = dataset.labels

# Load fsaverage5 surfaces
surf_lh, surf_rh = load_fsa5()

plot_hemispheres(surf_lh, surf_rh, array_name=Gsub.gradients_[:,0], size=(1200, 400), cmap='viridis_r',color_bar=True, zoom=1.5)


ERROR:
--------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-36-36f9cba88841> in <module>
     16 #plot_hemispheres(surf_lh,surf_rh, size=(800, 200))
     17 # # # sphinx_gallery_thumbnail_number = 2
---> 18 plot_hemispheres(surf_lh, surf_rh, array_name=grad, size=(1200, 400), cmap='viridis_r',color_bar=True, zoom=1.5)

~\Anaconda3\envs\Graph\lib\site-packages\brainspace\vtk_interface\decorators.py in _wrapper_wrap(*args, **kwds)
     39         def _wrapper_wrap(*args, **kwds):
     40             args, kwds = _wrap_input_data(args, kwds, *xargs, skip=skip)
---> 41             data = func(*args, **kwds)
     42             return data
     43         return _wrapper_wrap

~\Anaconda3\envs\Graph\lib\site-packages\brainspace\plotting\surface_plotting.py in plot_hemispheres(surf_lh, surf_rh, array_name, color_bar, color_range, label_text, cmap, nan_color, zoom, background, size, interactive, embed_nb, screenshot, filename, scale, transparent_bg, **kwargs)
    526         for an in array_name:
    527             if isinstance(an, np.ndarray):
--> 528                 name = surf_lh.append_array(an[:n_pts_lh], at='p')
    529                 surf_rh.append_array(an[n_pts_lh:], name=name, at='p')
    530                 array_name2.append(name)

~\Anaconda3\envs\Graph\lib\site-packages\brainspace\vtk_interface\wrappers\data_object.py in append_array(self, array, name, at, convert_bool, overwrite)
    212 
    213         if at in ['point', 'p']:
--> 214             _array_overwrite(self.PointData, to_point)
    215         elif at in ['cell', 'c']:
    216             _array_overwrite(self.CellData, to_cell)

~\Anaconda3\envs\Graph\lib\site-packages\brainspace\vtk_interface\wrappers\data_object.py in _array_overwrite(attributes, has_same_shape)
    209                                   'exists.')
    210             else:
--> 211                 raise ValueError('Array shape is not valid.')
    212 
    213         if at in ['point', 'p']:

ValueError: Array shape is not valid.

**Comment by OualidBenkarim** [comment]
Hi Angelika, 

The shape of conn_matrix is 1000x1000, right? And the size of the gradient (Gsub.gradients_[:,0]) is 1000. But surf_lh.n_points = 10242 and surf_rh.n_points = 10242. You need to map the parcellated data (1000) to the original size (20484). Here is an example:

`from nilearn import datasets`

Load schaefer 1000 parc  -- This is a nifti image, not a surface!
```
dataset = datasets.fetch_atlas_schaefer_2018(n_rois=1000, yeo_networks=7, 
                               resolution_mm=1)
atlas_filename = dataset.maps
labels = dataset.labels

```

Load example timeseries for 1 subject
```
data = datasets.fetch_development_fmri(n_subjects=1)
fmri_filenames = data.func[0]
```
Mask ts
```
from nilearn.input_data import NiftiLabelsMasker
masker = NiftiLabelsMasker(labels_img=atlas_filename, standardize=True,
                           memory='nilearn_cache', verbose=5)

time_series = masker.fit_transform(fmri_filenames)  # time_series is (168, 1000)
```

Build connectivity matrix 
```
import numpy as np
conn_matrix = np.corrcoef(time_series.T)  # conn_matrix is 1000x1000
```

Build gradients
```
from brainspace.gradient import GradientMaps
Gsub = GradientMaps(n_components=10, random_state=0, alignment="procrustes",
                      approach="dm")
Gsub.fit(conn_matrix, sparsity=0.9)  # shape of Gsub.gradients_[:, 0] is 1000
```

Load fsa5
```
from brainspace.datasets import load_fsa5
surf_lh, surf_rh = load_fsa5()
```

Here we need to map the gradient to the original size of fsa5. We need the 1000 Schaefer parcellation in fsa5. You can donwload the parcellation from github: https://github.com/ThomasYeoLab/CBIG/blob/master/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations/FreeSurfer5.3/fsaverage5/labe/lh.Schaefer2018_1000Parcels_7Networks_order.annot
```
import nibabel as nb

surf_labels_lh = nb.freesurfer.read_annot('/path/to/lh.Schaefer2018_1000Parcels_7Networks_order.annot')[0]
surf_labels_rh = nb.freesurfer.read_annot('/path/to/rh.Schaefer2018_1000Parcels_7Networks_order.annot')[0]
surf_labels_rh[surf_labels_rh != 0] += 500  # different labels for lh and rh
surf_labels = np.concatenate([surf_labels_lh, surf_labels_rh])

mask = surf_labels != 0  # discard medial wall
```

Map gradient to parcellation in surface
```
from brainspace.utils.parcellation import map_to_labels
grad = map_to_labels(Gsub.gradients_[:, 0], surf_labels, mask=mask, fill=np.nan)
```

Plot parcellation and first gradient
```
from brainspace.plotting import plot_hemispheres
plot_hemispheres(surf_lh, surf_rh, array_name=[surf_labels, grad], 
    size=(1200, 400),  cmap=['tab20', 'viridis_r'], color_bar=True, 
    zoom=1.5, label_text=['Schaefer\n1000', 'First\ngradient'])

```

**Comment by AngelikaZa** [comment]
Thank you, this works perfectly!
(Had tried map_to_labels but used the MNI not surface version of Schaefer.) 
Thank you again, 
Bw
Angelika

**Comment by acamargofb** [comment]
I am following this example, but I got this problem in the last step:


---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_24290/2584315120.py in <module>
      2 plot_hemispheres(surf_labels_lh, surf_labels_rh, array_name=[surf_labels, grad], 
      3     size=(1200, 400),  cmap=['tab20', 'viridis_r'], color_bar=True,
----> 4     zoom=1.5, label_text=['Schaefer\n1000', 'First\ngradient'])

~/Aldo/Research/code/BrainSpaceEnv/lib/python3.7/site-packages/brainspace/vtk_interface/decorators.py in _wrapper_wrap(*args, **kwds)
     39         def _wrapper_wrap(*args, **kwds):
     40             args, kwds = _wrap_input_data(args, kwds, *xargs, skip=skip)
---> 41             data = func(*args, **kwds)
     42             return data
     43         return _wrapper_wrap

~/Aldo/Research/code/BrainSpaceEnv/lib/python3.7/site-packages/brainspace/plotting/surface_plotting.py in plot_hemispheres(surf_lh, surf_rh, array_name, color_bar, color_range, label_text, layout_style, cmap, nan_color, zoom, background, size, interactive, embed_nb, screenshot, filename, scale, transparent_bg, **kwargs)
    551         layout = [layout] * len(array_name)
    552         array_name2 = []
--> 553         n_pts_lh = surf_lh.n_points
    554         for an in array_name:
    555             if isinstance(an, np.ndarray):

AttributeError: 'numpy.ndarray' object has no attribute 'n_points'
