### ISSUE TITLE
Changing colorbar labels

### ISSUE THREAD

**Issue by kristianeschenburg** [MICA-MNI/BrainSpace#18]
Hi

Thank you for developing this package!  I would like to change the tick labels on the colorbars, but I am not very familiar with VTK.  I have found the 'cb__' kwargs parameter, and can change the colorbar size (width and height).

I would like to be able to specify what to display at the colorbar ticks i.e. instead of [max(scalar map), min(scalar map)], I would like to display ['some text', 'some other text'].  How can I do this?

Thanks!

**Comment by OualidBenkarim** [comment]
Yep, that's a bit complicated with our current version, but here's a workaround

```python

# we have to work with the plotter
p = plot_hemispheres(surf_lh, surf_rh, array_name='yeo7', color_bar=True,  
size=(400, 100), zoom=1.25, return_plotter=True)

# Get the renderer with the colorbar
ren = p.renderers[4][0]

# Get colorbar
cb = ren.actors2D[0]

# Hide labels
cb.drawTickLabels = False

cb.height = 0.5
cb.width = 0.5
cb.position = (0.25, 0.25)

# Add your own
textProperty= {'color': (0, 0, 0), 'italic': False, 'shadow': False, 'bold': True, 'fontFamily': 'Arial', 
               'fontSize': 22, 'justification': 'centered', 'verticalJustification': 'centered'}
kwds_text = dict(positionCoordinate={'coordinateSystem': 'normalizedViewport'},  textProperty=textProperty)

# Adjust positions!
ren.AddTextActor(input='Text 1', position=(0.65, 0.3), **kwds_text)
ren.AddTextActor(input='Text 2', position=(0.65, 0.7), **kwds_text)

# You will probably have to adjust the positions when you change size or scale
p.show(embed_nb=False, interactive=False, scale=3)
```

And it looks like this:

![colorbar](https://user-images.githubusercontent.com/5702442/84951683-c5618980-b0be-11ea-89cb-58c8c32a3195.png)

Hope this helps

**Comment by kristianeschenburg** [comment]
Thank you!  This will work for my current purpose.
