### ISSUE TITLE
Comparing groups and projecting to 3D/4D volumes/meshes in BrainSpace (Python)

### ISSUE THREAD

**Issue by shawnrhoads** [MICA-MNI/BrainSpace#19]
Hello! 

I am trying to figure out the best way to compare gradient maps between groups after determining gradient using BrainSpace in Python. My current implementation computes individual-level gradient maps, then aligns them with a Procrustes transformation. See the following code:

```
import numpy as np
from brainspace.gradient import GradientMaps
from brainspace.gradient.alignment import ProcrustesAlignment 

#conn_matrices is list of symmetrical functional connectivity 
#   matrices as np.arrays for each subject -- using 400 Schaefer atlas

subj_gradients = [] #init list for GradientMaps objects
for index, subj in enumerate(conn_matrices):
    print(index) #print subject index to screen
    g_ind = GradientMaps(kernel='normalized_angle', random_state=0)
    g_ind.fit(subj)
    subj_gradients.append(g_ind.gradients_)

# subj_gradients is now a list of n_subject numpy arrays with shape: 
#    n_parcels x n_components 

# Procrustes align all subjects
# using ProcrustesAlignment() because the method in `GradientMaps` class 
#   (setting alignment='procrustes') only works for two group-level 
#   functional connectivity matrices
align_class = ProcrustesAlignment()
aligned_subjs = align_class.fit(subj_gradients)
```

Now, aligned_subjs.aligned_ is also a list of n_subject numpy arrays (with shape: n_parcels x n_components). Upon visual inspection, this alignment method seems to work pretty well across individuals! Please let me know if there is another recommended approach though.

To compare groups at each parcel, can I just conduct a non-parametric independent-samples t-test (of sorts)? Do I need to account for the spatial autocorrelation that is resolved through a method similar to the spin permutation test?

Furthermore, I am wondering BrainSpace contains any functionality to easily save any of the above instances as 3D/4D volumes or meshes? For example, can I project a `GradientMaps` class computed in BrainSpace to a 4D volume with each volume containing data from one of the gradient maps?

Thanks so much for your help!

**Comment by ReinderVosDeWael** [comment]
Hi,

The recommended method for alignment is to provide all connectivity matrices to the GradientMaps object simultaneously with the alignment parameter set to 'procrustes' (see https://brainspace.readthedocs.io/en/latest/python_doc/auto_examples/plot_tutorial2.html#gradient-alignment).

If you want to compare the gradients to other markers then I would still recommend accounting for spatial autocorrelation. Note that spin test can be defined in many different ways for parcel-based data (see slide 28 and onwards of https://figshare.com/articles/Methods_matter_The_impact_of_methodological_variability_in_network_neuroscience/12056133/1), and BrainSpace only natively implements a vertex-level spin test. Moran Spectral Randomization (implemented in BrainSpace) may provide an alternative for your data, or you could use variogram matching (see https://brainsmash.readthedocs.io/en/latest/).

There's currently no support for GradientMaps to volume saving, but it's in the works. If you're willing to get experimental then there's an early dev version of grad2fmrivols() here https://github.com/ReinderVosDeWael/BrainSpace/blob/grad2vol_hack/brainspace/utils/volflow.py, but use this with care as this function is still under construction.
