### ISSUE TITLE
diffusion time default value discrepancy 

### ISSUE THREAD

**Issue by NicolasNin** [MICA-MNI/BrainSpace#20]
Hi,

The following may be on purpose (I find it a bit inconsistent though).

In gradient/embedding.py , the class DiffusionMaps has a default diffusion time value set to 1, I believe it should be 0.
The documentation of the class says the default is 0, also the function doing the work "diffusion_mapping" has default at 0.

A GradientMaps would inherit this time diffusion of 1, when doing something like in the documentation ie:

```python
gm = GradientMaps(n_components=2, approach='dm', kernel='normalized_angle')
gm.fit(m) #this would have diffusion time of 1
```

--
Nicolas Ninin

**Comment by OualidBenkarim** [comment]
Hi Nicolas,

Yes, that's true. To avoid any confusion, diffusion time should be set to 0 in the docstrings and also for diffusion_mapping.

Thanks!
Oualid
