### ISSUE TITLE
problem with VTK for plot_hemispheres

### ISSUE THREAD

**Issue by 5Elise** [MICA-MNI/BrainSpace#25]
I'm stuck at the plot_hemispheres line

I get this error message, it seems like it's a problem with vtk and not brai space but would anyone know how to solve this VTK issue?

ERROR: In /work/standalone-x64-build/VTK-source/Rendering/OpenGL2/vtkXOpenGLRenderWindow.cxx, 
line 273
vtkXOpenGLRenderWindow (0x3b33610): bad X server connection. DISPLAY=Aborted (core dumped)

**Comment by ReinderVosDeWael** [comment]
Sorry I missed this issue earlier. I'm not too familiar with VTK's inner workings. That being said, this looks to me like VTK can't connect to your display. One possible cause is that you're running plot_hemispheres whilst SSHed into a remote computer. If that's the case, then this _might_ be resolved by running ssh with the -X parameter (on Linux/macOS; I don't know the Windows equivalent). 

If that doesn't help then I recommend you ask for assistance from VTK's support.
