### ISSUE TITLE
fsaverage6 plot_hemispheres

### ISSUE THREAD

**Issue by sophiatinh** [MICA-MNI/BrainSpace#26]
Thank you for the very helpful package for analysis. I am pretty new to this area so I have a question regarding the surface space. My connectivity matrix was formulated using the Schaefer 400 parcellation from data mapped onto the fsaverage6 surface. I noted that the labels and surfaces here are all Conte69 surface. I am just wondering if it is possible to plot the gradient with fsaverage6? Does that actually even matter at all? Much thanks!

**Comment by ReinderVosDeWael** [comment]
Great to hear you're enjoying BrainSpace. Yes all our tutorial data was provided on the Conte69 surface, but our functions are capable of handling any surface/parcellation, provided that you load them yourself.

BrainSpace's surface readers ([MATLAB](https://brainspace.readthedocs.io/en/latest/pages/matlab_doc/main_functionality/read_surface.html) / [Python](https://brainspace.readthedocs.io/en/latest/generated/brainspace.mesh.mesh_io.read_surface.html#brainspace.mesh.mesh_io.read_surface)) can load some of the common neuroimaging formats. If your surface is stored in a different format, then I recommend you convert it to one of the accepted formats. Next you'd also load your parcellation scheme as a double/numpy array. You should then be able to plot your data using the code presented in Tutorial 1 ([MATLAB](https://brainspace.readthedocs.io/en/latest/pages/matlab_doc/examples/tutorial_1_gradient_creation.html) / [Python](https://brainspace.readthedocs.io/en/latest/python_doc/auto_examples/plot_tutorial1.html#sphx-glr-python-doc-auto-examples-plot-tutorial1-py)).

Let me know if that helps and/or if anything is unclear.

**Comment by sophiatinh** [comment]
Thank you so much for your prompt reply! I have managed to make it work with my surface using the convert_surface function.
I have another question regarding gradient analysis. If I would like to compare gradient value between individuals, or summarizing gradient values, does aligning the gradient using the reference gradient that is constructed by the group average correlation works?
Also, it seems like the correlation matrix utilized as input in the example has not been Fisher z-transformed. Is there a reason why the untransformed matrix is preferred?
Thank you so much again!

**Comment by ReinderVosDeWael** [comment]
> I have another question regarding gradient analysis. If I would like to compare gradient value between individuals, or summarizing gradient values, does aligning the gradient using the reference gradient that is constructed by the group average correlation works?

Ideally you'd align individuals to a holdout group. However, if this is not possible within your study design (e.g. due to insufficient sample size, no comparable external dataset), then aligning to the group average should be OK. 

> Also, it seems like the correlation matrix utilized as input in the example has not been Fisher z-transformed. Is there a reason why the untransformed matrix is preferred?

I don't believe the gradient field has settled on an answer here. For example, Margulies et al used the r-matrix  (Margulies et al., 2016, PNAS; SI Methods)] whereas in some of our lab's work we've used the z-matrix (Vos de Wael et al., 2018, PNAS; SI Methods). I haven't seen any formal comparison of the effects of using the r-matrix or z-matrix on the resultant gradients, and as far as I'm aware it doesn't make a substantial difference (at least in rs-fMRI).

**Comment by sophiatinh** [comment]
Thank you so much for your help! All your advice and suggestion have been incredibly helpful.
