### ISSUE TITLE
Matlab - wrong dimension for splitting of the gradients after ja

### ISSUE THREAD

**Issue by manea006** [MICA-MNI/BrainSpace#28]
I believe that at [this line ](https://github.com/MICA-MNI/BrainSpace/blob/666e43c6037418d8ffc150fd68c3c5f52867739f/matlab/%40GradientMaps/fit.m#L88) the wrong dimension is taken. This is not a problem for symmetrical input matrices, but for non-symmetrical input matrices it tries to [split the aligned (ja) gradients](https://github.com/MICA-MNI/BrainSpace/blob/666e43c6037418d8ffc150fd68c3c5f52867739f/matlab/%40GradientMaps/fit.m#L118) with the number of targets rather than seeds. I also checked the python code and for that, it seems to be in order. Let me know what you think and if I should submit a pull request

**Comment by ReinderVosDeWael** [comment]
Good catch! Yes, that is indeed a bug and your assessment seems correct: this should not affect joint alignment of symmetric matrices, but it will cause wrong dimensions in asymmetric matrices. 

Fortunately, it looks like an easy fix. I've published a PR (#29) to address this. Please have a go with it and let me know if you encounter any further issues.

**Comment by manea006** [comment]
Thank you!
