### ISSUE TITLE
Matlab - out of memory error for matrix sparsification

### ISSUE THREAD

**Issue by manea006** [MICA-MNI/BrainSpace#31]
For very large matrices I had an out of memory error at [this line](https://github.com/MICA-MNI/BrainSpace/blob/666e43c6037418d8ffc150fd68c3c5f52867739f/matlab/%40GradientMaps/GradientMaps.m#L187). Matlab memory usage was much lower than the total memory available. However, with the following replacement it worked.

```
p = prctile(data, p.Results.sparsity);
for i = 1: length(data)
	col = data(:, i);
	col(col<p) = 0;
	data(:, i) = col;
end
```

**Comment by ReinderVosDeWael** [comment]
Ah, the CPU vs. memory trade-off. The current BrainSpace implementation should run faster whereas your proposed solution should be more memory efficient. Speed probably isn't much of an issue in this particular case though. I'll mark this as a future enhancement.
