### ISSUE TITLE
Plotting Gradient using plot_hemispheres

### ISSUE THREAD

**Issue by sophiatinh** [MICA-MNI/BrainSpace#35]
Hi,
Using the gradient_in_euclidean function, we can clearly note the area that has not been covered in the scan as seen by the grey mask. However, the plot_hemispheres mask uses dark blue which is the same color as other regions of the brain which has lower gradient value. Is there a way for me to customize so that the area where the label value = 0 (aka. not covered in scan/parcellation) can be set in gray/different color scheme?

Much thanks!

**Comment by ReinderVosDeWael** [comment]
Hi,

Both functions behave identically in that the mask is assigned a value like any other from the colormap, gradient_in_euclidean simply uses a custom color map. To get a different color for the colormap you'll want to set a custom colormap wherein the lowest value is the color that you want for the mask, set this colormap for all axes, and set areas that you want removed to -inf. Note that MATLAB's behavior with this -inf trick can sometimes be a bit finicky, but there's not much we can do about that from our end. 

Unfortunately programming this (see below) is somewhat unintuitive. In the current development version of BrainSpace I've reprogrammed plot_hemispheres to be better at altering color limits and color maps, but for now this is the solution.

```MATLAB
% Load a gradient, set nans to -inf.
g = load_gradient('fc',1);
g(isnan(g)) = -inf;

% Load and plot surfaces.
[left_surf, right_surf] = load_conte69();
h = plot_hemispheres(g,{left_surf, right_surf});

% Set custom colormap.
my_cmap = [.7 .7 .7; parula(256)];
colormap(my_cmap);

% Notice how the bottom of the gradient is also masked now.
% Lets fix that.
my_limits = [-7 9];
for ii = 1:numel(h.axes)
    % Set custom limits for each axis
    h.axes(ii).CLim = my_limits;
end

% Set custom limits for the colorbar.
h.cb.Limits = my_limits;
h.cb.Ticks = my_limits;
```

**Comment by sophiatinh** [comment]
That piece of code works perfectly! Much thanks!
