### ISSUE TITLE
Nifti to fsaverage surface 

### ISSUE THREAD

**Issue by seralouk** [MICA-MNI/BrainSpace#36]
Hello,

First of all, thanks for this amazing repo.

I have a 3D nifti file that I would like to project to the fsaverage surface for a nice visualization output.
My nifti file is already in MNI space.

Is that possible using this tool?

Data:https://easyupload.io/260ldc
Pass: makis

**Comment by ReinderVosDeWael** [comment]
Hi,

Unfortunately we do not provide this functionality as part of BrainSpace. You may want to look at the Human Connectome Project's Workbench Tools for this.  Once you have the data on fsaverage you could read it into Python/MATLAB and use BrainSpace for the visualization. 

Cheers,

Reinder

**Comment by seralouk** [comment]
thanks
