### ISSUE TITLE
misalignment between left and right diffusion maps (matlab version)

### ISSUE THREAD

**Issue by lqcheng2017** [MICA-MNI/BrainSpace#40]
Hi!

I' trying to generate diffussion maps for the left and right hemispheres using following codes:

gm = GradientMaps('kernel','na','approach','dm','n_components',2, 'alignment', 'pa', 'random_state', 10);
gm = gm.fit({left_fc_matrix, right_fc_matrix});

however, directions of the principal gradients between the two hemispheres are opposite. 
Could you have any suggestions about how to align the two principal gradients? Thank you very much. 

Best,
Luqi

![G](https://user-images.githubusercontent.com/33225614/113985893-386f0300-987f-11eb-861f-293f313acdbd.png)

**Comment by ReinderVosDeWael** [comment]
Hi,

I suspect the rotation isn't working well because you're only generating two gradients - do you find the same results with a higher number for n_components?

**Comment by lqcheng2017** [comment]
Hi, 

Thanks for your quick reply. 
I didn't notice the _field_ "aligned" in the _structure array_ "gm". I displayed the results in the _field_  "aligned" and they looked very well. 

Best,
Luqi
