### ISSUE TITLE
Subject list for group connectivity matrices

### ISSUE THREAD

**Issue by danjgale** [MICA-MNI/BrainSpace#41]
I was wondering if the list of HCP subjects used for the group functional connectivity matrices with `load_group_fc`/`load_group_mpc` was available. My understanding/assumption is that these subsets of HCP data are based on the selection procedures described in [Vos de Wael et al (2018)](https://www.pnas.org/content/115/40/10154), but I'm not 100% certain in that. 

I'm looking to compute similar connectivity matrices on the samples used in Vos de Wael et al (2018), but I also think it would be great if the documentation could clarify the source of the group connectivity matrices.

**Comment by ReinderVosDeWael** [comment]
Hi, 

You are mostly correct; all but the MPC data is derived from Vos de Wael et al (discovery dataset). The MPC dataset is derived from Paquola et al, 2019 as noted in tutorial 2.

Although that information is available in the current documentation it is, indeed, far too well hidden. I'll try to fix this in the next update. If you need these subject lists soon, send me an e-mail for the Vos de Wael et al subject list or contact Casey Paquola for the Paquola et al subject list.

**Comment by danjgale** [comment]
Ah okay, I missed that at the bottom of tutorial 2. Perhaps including this information in each function's docstring might be the most upfront approach.
