### ISSUE TITLE
Bug in utils.py?

### ISSUE THREAD

**Issue by DimuthuHemachandra** [MICA-MNI/BrainSpace#5]
I am getting an error in this code BrainSpace/brainspace/gradient/utils.py
Here k is 1-.9 which is a float. But then it gets multiplied by nc and tuned into an int. That makes it a zero. I think you are missing *100 here?
    if not is_thresh:
        nr, nc = s.shape
        if isinstance(k, float):
            if not 0 < k < 1:
                raise ValueError('When \'k\' is float, it must be 0<k<1.')
            k = int(nc * k)

        if k <= 0:
            raise ValueError('Cannot select 0 elements.')

**Comment by OualidBenkarim** [comment]
I don't see any problem with the code. If you wanna keep 10%, then you are going to have `int(0.1 * nc)` nonzero elements per row. If the number of columns is smaller than 10, then you will get rows with all zeros.

**Comment by DimuthuHemachandra** [comment]
When it is less than 10, k = int(nc * k) will return a 0. Then next line is if k <= 0:
        raise ValueError('Cannot select 0 elements.'). Code stops there with that error.

**Comment by OualidBenkarim** [comment]
Yes, that's correct. When that happens, the result would be a matrix will all zeros, that's why the exception. You can try increasing `k` (30% for example)

**Comment by DimuthuHemachandra** [comment]
Oh I see. Where can I set the k value without actually editing your code. Gradientmap has no argument for k?

**Comment by OualidBenkarim** [comment]
You can change the `sparsity` in the `fit` method of `GradientMaps`. Then the value of k is: k=1.-sparsity

**Comment by DimuthuHemachandra** [comment]
Ok. Thank you very much.
