### ISSUE TITLE
Procrustes alignment may reorder the  embedding components or/and change the gradient values locally

### ISSUE THREAD

**Issue by debinz** [MICA-MNI/BrainSpace#52]
Hi!

Thank you for developing this awesome tool!

I am trying to map the gradients in individual connectivity and age-group-wise connectivity in a longitudinal dataset, and I used Procrustes alignment to align these gradients to a template (gradient computed based on averaged connectivities of all subjects). I found the alignment may reorder the embedding components or/and change the gradient values locally.  Besides, I also found the eigenvalue vector 'lambda' didn't change after doing this alignment, Does it mean the vector still corresponds to the original gradients, not the aligned one? I'm puzzling whether this operation may weaken the age-related changes of the gradients. Can you give me some advice about that? any suggestions will be welcome. Thank you! 

Have a good day!

Zeng

**Comment by ReinderVosDeWael** [comment]
Hi.

Procrustes rotates the gradients in n-dimensional space so reordering or changing values at particular vertices is all intended behavior. The lambda field indeed corresponds to pre-aligned gradients. As of yet, there is no way to alter the lambda's to account for the rotation.

Cheers,

Reinder
