### ISSUE TITLE
The gradients reversed when remove some features 

### ISSUE THREAD

**Issue by HusBunia** [MICA-MNI/BrainSpace#53]
Hi:
I used the genetic data to build my network and correlated it with the other MRI-based network gradients. 2000 genes were included in my network, and  I want to estimate the importance of one gene. Thus, I removed the gene from my network. As a result, I found the gradients were changed from positive to negative, e.g. from 0.63 to -0.62. However, after Procrustes alignment, the alignment gradients return a positive result, such as 0.62. I want to know if the result is reasonable, and the alignment is necessary?
Thank you for providing such a convenient tool. 

Ray

**Comment by OualidBenkarim** [comment]
The sign of the gradients is not relevant here, you can simply change the sign...or align them if you think there may be other differences.

**Comment by HusBunia** [comment]
> The sign of the gradients is not relevant here, you can simply change the sign...or align them if you think there may be other differences.

Hi: 
Thanks for your answer! 
Could I understand the sign of the gradients was meanless? Because I have calculated the relationship between two different gradients. Does that mean the sign of the correlation is no matter in my study? Or the significance of the correlation was the only thing I should consider. 
Thanks again for your help!

**Comment by OualidBenkarim** [comment]
Yes! Gradients are eigenvectors, and as such their sign is arbitrary

**Comment by HusBunia** [comment]
> Yes! Gradients are eigenvectors, and as such their sign is arbitrary

Thanks! I have learned that.
