### ISSUE TITLE
The results for gradients 1 and 2 are reversed

### ISSUE THREAD

**Issue by HuXinUESTC** [MICA-MNI/BrainSpace#56]
Hi, Thank you for noticing this issue.
When I used the BrainSpace to compute the gradeint, I got and visualized the gradient 1 and gradient 2. Contrary to the canonical gradients established by Margulies(2016), it seems that my Gradient 1 is similar to canonical gradient2, while my Gradient 2 is similar to canonical gradient1. Has anything like that ever happened to you? Could you provide some suggestion to me ? My computing environment is  Matlab 2018a and BranSpace 0.1.1

**Comment by HuXinUESTC** [comment]
PS: all my data are normal adults.

**Comment by ReinderVosDeWael** [comment]
This is a fairly common issue that may occur when the eigenvalue of the sensory gradient is higher than the transmodal gradient's eigenvalue. In general, I wouldn't worry about this and just continue your analysis with these gradients.

Processing strategies may make some difference in this matter. Anecdotally, I've seen the normalized angle kernel change gradient position more often than the cosine similarity kernel.

**Comment by HuXinUESTC** [comment]
Got it, thanks a lot. Maybe we should define every gradient according to the extreme location of the gradient axis, rather than the propotion of explaned variance.

**Comment by AstonshisL** [comment]
胡学长，请问是否可以跟您联系？我现在就读于CQUPT，关于梯度的问题研究了许久但无法解决，不知道可否请教您
