### ISSUE TITLE
How to get the FC matrix from my own data?

### ISSUE THREAD

**Issue by zbwcncq** [MICA-MNI/BrainSpace#57]
I can run BrainSpace based on the example data, but I noted that the FC matirx used in Brainspace was different from which I usually used, I want to get the FC matrix from my own rs-fMRI data, would you please provide a guideline about the preprocessing of rs-fMRI data and construction of FC matrix ?

**Comment by PeerHerholz** [comment]
Hi @zbwcncq,

please note that the computation/derivation of `FC` or other `connectivity matrices` is not part of `BrainSpace` itself but assumed to be conducted elsewhere. For example, if you're using `python` you could employ the [nilearn package](https://nilearn.github.io/stable/index.html). Regarding `matlab`-based tools @ReinderVosDeWael might be able to provide some pointers. The `BrainSpace` docs furthermore contain tutorials that showcase the respectively necessary steps, e.g. [here for `python`](https://brainspace.readthedocs.io/en/latest/python_doc/auto_examples/plot_tutorial0.html#sphx-glr-python-doc-auto-examples-plot-tutorial0-py).

HTH, cheers, Peer

**Comment by ReinderVosDeWael** [comment]
Woops - I missed this issue.
 
Yes indeed, as Peer mentioned, deriving the input (connectivity) matrix is not part of the BrainSpace toolkit, although our Python tutorial 0 does show an example. Several other tools exist that may help derive FC matrices (e.g. [micapipe](https://github.com/MICA-MNI/micapipe)). 

I hope that helps.
