### ISSUE TITLE
Inverse transform embedding value to surface, save as file

### ISSUE THREAD

**Issue by htwangtw** [MICA-MNI/BrainSpace#58]
As BrainSpace currently supports plotting the embedding onto the surface, I wonder would it be helpful to have a inverse transform function so people can save the embedding as surface files. As BrainSpace currently supports plotting the embedding onto the surface, would it be possible to expose the private functions that does the inverse transformation?

Having a brief look I believe this function might be the core of it?
https://github.com/MICA-MNI/BrainSpace/blob/1fb001f4961d3c0b05b7715f42bcc362b31b96a5/brainspace/plotting/utils.py#L82-L102

cc @anproulx

**Comment by ReinderVosDeWael** [comment]
Hi Hao-Ting

This seems like it'd be helpful to me, but @OualidBenkarim is better versed in the specifics of the Python implementation than I am.

@OualidBenkarim what are your thoughts?

**Comment by OualidBenkarim** [comment]
Hi @htwangtw 

I'm not sure I fully understand the question. If you want to save the gradients (aka embedding) in a surface, you can try:

```python
surf = load_conte69(join=True)
surf.append_array(mygrad, name="gradient1")  # where 'mygrad' is the first gradient for example
# Now surf.PointData["gradient1"] contains the first gradient

write_surface(surf, "/path/to/my_surf_name.vtp'') # save surface with gradient

```

Is this it or am I not getting it?

**Comment by htwangtw** [comment]
> Hi @htwangtw
> 
> I'm not sure I fully understand the question. If you want to save the gradients (aka embedding) in a surface, you can try:
> 
> ```python
> surf = load_conte69(join=True)
> surf.append_array(mygrad, name="gradient1")  # where 'mygrad' is the first gradient for example
> # Now surf.PointData["gradient1"] contains the first gradient
> 
> write_surface(surf, "/path/to/my_surf_name.vtp'') # save surface with gradient
> ```
> 
> Is this it or am I not getting it?

You are totally right - good to know there's existing function for it. Not sure why I didn't find it in the first place.
~On an related note, would it worth it to store it in some more standard surface data format? (GIFTI or CIFTI)~

I dug through the code a bit more and realised what I was thinking of is already supported. The inverse transformation was part of the [surface mesh class and vtk wrapper](https://brainspace.readthedocs.io/en/latest/python_doc/vtk_wrap.html?highlight=append_array#data-object-wrappers). 
I was more thinking along the line of doing everything with numpy array and nibabel image class before saving, hence missed the whole vtk wrapper:
```python
# given a parcellation dlabel file (Schaefer2018_400Parcels_7Networks_order.dlabel.nii) and a correlation_matrix using the ROIs

import nibabel as nb
import numpy as np

labels = nb.load("path/to/lable.dlabel.nii")
gradient_map  = GradientMaps().fit(correlation_matrix)
gradients = np.zeros((n_vertices, gm.gradients_.shape[1]))
for i, lables in enumerate(labels):
    gradients[parcellation == l] = gm.gradients_[i]

# dump the numpy array to desired output format
```
I will consider this issue solved and I failed to find a solution due to misunderstanding of design choice :sweat_smile:
