### ISSUE TITLE
error handling of 0 rows

### ISSUE THREAD

**Issue by jordandekraker** [MICA-MNI/BrainSpace#62]
Trying to fit data that contains a row of entirely 0s currently returns all NaNs in the output gradients when `kernel='cs'` or `kernel='na'`  (python version). Ideally, this should throw an error or perhaps rows containing all 0s should simply be discarded before this line:
https://github.com/MICA-MNI/BrainSpace/blob/528452f0a3e7cc671031aa1ecd6ed1b2e4d68a89/brainspace/gradient/kernels.py#L27

**Comment by ReinderVosDeWael** [comment]
The MATLAB implementation resolves this by explicitly checking for inf/nan in the affinity matrix. We could implement something similar in Python

https://github.com/MICA-MNI/BrainSpace/blob/528452f0a3e7cc671031aa1ecd6ed1b2e4d68a89/matlab/%40GradientMaps/fit.m#L101-L103
