### ISSUE TITLE
Latest (0.1.3) not compatible with new vtk

### ISSUE THREAD

**Issue by mgxd** [MICA-MNI/BrainSpace#74]
* **What is the current behavior?**
The newest VTK release candidate (`9.2.0rc1`) is incompatible.

* **Please provide the steps to reproduce and if possible a minimal demo of the problem**.
```
$ python -c "from brainspace.mesh.mesh_io import read_surface"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mathiasg/.pyenv/versions/nipreps/lib/python3.10/site-packages/brainspace/mesh/__init__.py", line 1, in <module>
    from . import (array_operations, mesh_elements, mesh_correspondence,
  File "/Users/mathiasg/.pyenv/versions/nipreps/lib/python3.10/site-packages/brainspace/mesh/array_operations.py", line 22, in <module>
    from . import mesh_elements as me
  File "/Users/mathiasg/.pyenv/versions/nipreps/lib/python3.10/site-packages/brainspace/mesh/mesh_elements.py", line 16, in <module>
    from ..vtk_interface import wrap_vtk, serial_connect
  File "/Users/mathiasg/.pyenv/versions/nipreps/lib/python3.10/site-packages/brainspace/vtk_interface/__init__.py", line 1, in <module>
    from .wrappers.base import (wrap_vtk, unwrap_vtk, wrap_vtk_array,
  File "/Users/mathiasg/.pyenv/versions/nipreps/lib/python3.10/site-packages/brainspace/vtk_interface/wrappers/__init__.py", line 1, in <module>
    from .base import BSVTKObjectWrapper
  File "/Users/mathiasg/.pyenv/versions/nipreps/lib/python3.10/site-packages/brainspace/vtk_interface/wrappers/base.py", line 15, in <module>
    from .utils import call_vtk, get_vtk_methods, is_numpy_string, is_vtk_string
  File "/Users/mathiasg/.pyenv/versions/nipreps/lib/python3.10/site-packages/brainspace/vtk_interface/wrappers/utils.py", line 15, in <module>
    from vtk.util.vtkConstants import VTK_BIT, VTK_STRING, VTK_UNICODE_STRING
ImportError: cannot import name 'VTK_UNICODE_STRING' from 'vtk.util.vtkConstants' (/Users/mathiasg/.pyenv/versions/nipreps/lib/python3.10/site-packages/vtkmodules/util/vtkConstants.py)
```

* **What is the expected behavior?**
No error

* **Please tell us about your computing environment:**
macOS 12.4
Python 3.10 with vtk 9.2.0rc1, but extends down to py3.7

**Comment by ReinderVosDeWael** [comment]
Hi,

Unfortunately we don't support early release candidates. If this bug persist when VTK 9.2.0 is released then we'll resolve this then. As VTK 9.1 does not support Python 3.10, this also means that BrainSpace is currently still incompatible with Python 3.10.

**Comment by mgxd** [comment]
@ReinderVosDeWael There are unofficial VTK wheels for 3.10, but this problem is also present for earlier python distributions, including 3.7.

How about setting a maximum supported VTK version in https://github.com/MICA-MNI/BrainSpace/blob/master/setup.py#L22? Then this problem won't affect installations if/when VTK 9.2.0 is released.

**Comment by ReinderVosDeWael** [comment]
I'm not convinced that these issues will persist in the final release of 9.2. 

The rc1 wasn't intended as a bug-free release candidate (c.f. https://discourse.vtk.org/t/vtk-9-2-0-release-cycle/8149) so making decisions based on this candidate release is quite preliminary.  

If the issues persist after the official 9.2 release then we can resolve it then.

**Comment by ghisvail** [comment]
> I'm not convinced that these issues will persist in the final release of 9.2.

"vtkUnicodeString and vtkUnicodeStringArray have been removed."

This is in the actual [changelog](https://gitlab.kitware.com/vtk/vtk/-/blob/master/Documentation/release/9.2.md).

> If the issues persist after the official 9.2 release then we can resolve it then.

They will. Better start dealing with it early with the wheels currently provided than wishing this change will be reverted somehow (it won't).

**Comment by ghisvail** [comment]
I provided a PR which should implement the necessary compat code to use both wheels from VTK 9.1 and 9.2 (assuming this is the only incompatibility issue).

**Comment by ghisvail** [comment]
For what it's worth, our unit tests now pass for all Python versions (including 3.10) with the fix I provided so it appears there are no other `ImportError` to deal with with VTK 9.2.

**Comment by OualidBenkarim** [comment]
Yep, this should work fine now. Thanks @ghisvail

**Comment by ReinderVosDeWael** [comment]
Perfect, thanks!

**Comment by ghisvail** [comment]
You're welcome. Would be great to get a release to avoid installing from GitHub 🙏
