### ISSUE TITLE
0.1.4 release for VTK pre-release compatibility

### ISSUE THREAD

**Issue by effigies** [MICA-MNI/BrainSpace#76]
A release (or pre-release) on PyPI that includes #75 would be appreciated. We run tests where we `pip install --pre` our whole dependency tree, and currently VTK having a pre-release is breaking with 0.1.3.

This would be easiest for me, but I know it's a chore for you, so if you don't have time to do it, we'll find a different solution.

**Comment by ReinderVosDeWael** [comment]
@OualidBenkarim do you have time for this soon? Otherwise I can have a look mid to late next week.

**Comment by OualidBenkarim** [comment]
Completely forgot about this :( It will be done by Monday

**Comment by effigies** [comment]
Thank you!
