### ISSUE TITLE
Different dimensions of timeseries and atlas

### ISSUE THREAD

**Issue by StephDocTUM** [MICA-MNI/BrainSpace#81]
Dear all,

I am using the fmriprep output which has the dimension of [325325, 238]. E.g. as in the example given using the atlas = datasets.fetch_atlas_surf_destrieux() only has 20484 regions. 
What do you suggest to fit the timeseries fmriprep output to an surface atlas?

Best,

**Comment by PeerHerholz** [comment]
Hi @StephDocTUM,

thank you very much for opening this issue.

I think there are several options you could try, including resampling the `fmriprep` output to the `atlas` of your choice or the other way around. The basic idea would be to use the `fmriprep` preproc.nii.gz` files in combination with the `destrieux` `atlas`? Maybe the [neuromaps](https://netneurolab.github.io/neuromaps/index.html) package could be helpful to obtain the respective files (e.g. example [here](https://netneurolab.github.io/neuromaps/auto_examples/plot_fetch_datasets.html#sphx-glr-auto-examples-plot-fetch-datasets-py))?

HTH, cheers, Peer

P.S.: there's also [neurostars](https://neurostars.org/) for all questions related to neuroimaging, etc.. It's a great community providing a lot of support. Questions like yours are definitely more than welcome there!

**Comment by zihuaihuai** [comment]
solved
