### ISSUE TITLE
Too slow when running gm.fit on vertice 

### ISSUE THREAD

**Issue by chenfei-ye** [MICA-MNI/BrainSpace#85]
Hi, 

Current version works fine (~minutes) when running gm.fit() with cosine/normalized_angle kernel for node-based connectivity matrix (e.g. 400 nodes for Schaefer atlas), but it could be really slow (~hours) when running on huge-size vertex-based connectivity matrix (e.g. 32k for fs_LR space, or 20k for fsaverage5 space). 

One way for speedup is using gpu-torch methed `torch.nn.functional.cosine_similarity(x[:, None, :], x[None, :, :], dim=-1)`, but CUDA out of memory becomes another problem. 

I suggest to replace [line 27](https://github.com/MICA-MNI/BrainSpace/blob/master/brainspace/gradient/kernels.py) with `1 - sklearn.metrics.pairwise_distances(x, metric = 'cosine')`. In my test of affinity matrix computing, sklearn method is more efficient than scipy method.

Chenfei

**Comment by OualidBenkarim** [comment]
Hi @chenfei-ye 

Yes, for big matrices the current implementation can be very slow, a pull request is welcome. 

Another way to do it is to compute your kernel before calling `gm.fit`:
```python

m = 1 - sklearn.metrics.pairwise_distances(x, metric = 'cosine')  # build kernel before
gm = GradientMaps(kernel=None, ...)  # use no kernel here

gm.fit(m)
```
