### ISSUE TITLE
How to save the hemisphere plots from the plotter?

### ISSUE THREAD

**Issue by RuiHe1999** [MICA-MNI/BrainSpace#86]
Hi,

Thanks for providing this useful toolkit. I have created a plotting.base.plotter using this code in python:

plotter = plot_hemispheres(surf_lh, surf_rh, array_name=grad, size=(1200, 400), 
                    cmap='viridis_r', color_bar=True, 
                  label_text=['Grad1', 'Grad2', 'Grad3', 'Grad4', 'Grad5', 
                              'Grad6', 'Grad7', 'Grad8', 'Grad9', 'Grad10'], 
                  zoom=1.5, embed_nb=False, return_plotter=True) 

I wonder if and how I can save the plotter as an image. 

Thanks
Rui

**Comment by OualidBenkarim** [comment]
Hi @RuiHe1999 

You can do it with `plotter.screenshot(filename,...)`

**Comment by RuiHe1999** [comment]
> plotter.screenshot(filename,...)

Thanks, it works!
