### ISSUE TITLE
Some problems about schaefer_1000

### ISSUE THREAD

**Issue by KongKongKongMaster** [MICA-MNI/BrainSpace#90]
* **What is the current behavior?**
I get functional connectivity matrix 1000*1000 and  gradient matrix of dimension 1000.
but  {plot_hemispheres}  function does not have schaefer_1000_conte69.csv. so I want to know that how to get file {schaefer_1000_conte69.csv}   and  plot gradient to surface.

**Comment by OualidBenkarim** [comment]
Schaefer 1000 parcellation is available now (see #96)
