### ISSUE TITLE
Questions about lambda values

### ISSUE THREAD

**Issue by shaokunzhao** [MICA-MNI/BrainSpace#92]
After .fit, lambda has a huge value, between 300 and 1200. Why is this ?

**Comment by ReinderVosDeWael** [comment]
In general, it's the value of lambdas relative to each other that's of interest, rather than their absolute values. Unless you've got some specific reason to worry about the lambdas, I wouldn't think much of this.

**Comment by shaokunzhao** [comment]
Thank you for your response, it is very helpful.
