### ISSUE TITLE
plot_hemispheres() returns <IPython.core.display.Image object>

### ISSUE THREAD

**Issue by rtang2100** [MICA-MNI/BrainSpace#97]
Hello,

I cannot get the plot to display or show when running the following commands:

plot_hemispheres(
    surfaces[0],
    surfaces[1],
    vertexwise_PICALM,
    color_bar=True,
    embed_nb=True,
    size=(1400, 200),
    zoom=1.45,
    nan_color=(0.7, 0.7, 0.7, 1),
    cb__labelTextProperty={"fontSize": 12},
)    

It always return <IPython.core.display.Image object>. If I use display(), it also doesn't work.

Thanks,
Catherine

**Comment by OualidBenkarim** [comment]
That's probably an issue with IPython. What do you get when you set `embed_nb=False`?

**Comment by acamargofb** [comment]
How do you do that, I mean how do I set embed_nb=False?

**Comment by acamargofb** [comment]
I am working on Jupyter-lab

**Comment by zihuaihuai** [comment]
It is a argument of this function 
```
plot_hemispheres(
surfaces[0],
surfaces[1],
vertexwise_PICALM,
color_bar=True,
*embed_nb=True,*
size=(1400, 200),
zoom=1.45,
nan_color=(0.7, 0.7, 0.7, 1),
cb__labelTextProperty={"fontSize": 12},
)
```
