### ISSUE TITLE
Calculation of FC matrix for Brainspace

### ISSUE THREAD

**Issue by Avijit-Chowdhury1** [MICA-MNI/BrainSpace#99]
Dear experts,

I am a novice at gradient analysis. From the tutorials, it seems that one needs a functional connectivity matrix of a certain resolution (e.g., 400x400 Schaffer parcellation) to calculate gradients. 

My question is, is this connectivity matrix calculated from data that has been normalized to the MNI volumetric space? I have seen other articles which mention that data was projected into freesurfer surface space with 10000 vertices. So the FC matrix is 10000x10000. Does the data have to be projected into surface space before calculating the connectivity matrix?

Also, what are the advantages (if any) of using a higher resolution (e.g., 400 vs. 10000 resolution)?

**Comment by OualidBenkarim** [comment]
Hi, @Avijit-Chowdhury1,

Sorry for the delayed reply.

For gradient analysis, you can provide a connectivity matrix of any resolution and in any space as long as you ensure the interpretation of the results is consistent with the input matrix. It could be volumetric or surface data, in subject or MNI space, etc

And about the advantages of the resolution, higher resolutions can reveal fine-grained details. But, again, this depends on your analysis goals and the available data

**Comment by zihuaihuai** [comment]
sovled
